/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "./osc-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_MeasGapConfigRrc_H_
#define	_MeasGapConfigRrc_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetupRelease_GapConfig;

/* MeasGapConfigRrc */
typedef struct MeasGapConfigRrc {
	struct SetupRelease_GapConfig	*gapFR2;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct MeasGapConfigRrc__ext1 {
		struct SetupRelease_GapConfig	*gapFR1;	/* OPTIONAL */
		struct SetupRelease_GapConfig	*gapUE;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasGapConfigRrc_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasGapConfigRrc;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasGapConfigRrc_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasGapConfigRrc_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetupRelease.h"

#endif	/* _MeasGapConfigRrc_H_ */
#include <asn_internal.h>
