/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "./osc-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_PDSCH_ServingCellConfig_H_
#define	_PDSCH_ServingCellConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "ServCellIndexRrc.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDSCH_ServingCellConfig__xOverhead {
	PDSCH_ServingCellConfig__xOverhead_xOh6	= 0,
	PDSCH_ServingCellConfig__xOverhead_xOh12	= 1,
	PDSCH_ServingCellConfig__xOverhead_xOh18	= 2
} e_PDSCH_ServingCellConfig__xOverhead;
typedef enum PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH {
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n2	= 0,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n4	= 1,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n6	= 2,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n10	= 3,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n12	= 4,
	PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH_n16	= 5
} e_PDSCH_ServingCellConfig__nrofHARQ_ProcessesForPDSCH;

/* Forward declarations */
struct SetupRelease_PDSCH_CodeBlockGroupTransmission;

/* PDSCH-ServingCellConfig */
typedef struct PDSCH_ServingCellConfig {
	struct SetupRelease_PDSCH_CodeBlockGroupTransmission	*codeBlockGroupTransmission;	/* OPTIONAL */
	long	*xOverhead;	/* OPTIONAL */
	long	*nrofHARQ_ProcessesForPDSCH;	/* OPTIONAL */
	ServCellIndexRrc_t	*pucch_Cell;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDSCH_ServingCellConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_xOverhead_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_nrofHARQ_ProcessesForPDSCH_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PDSCH_ServingCellConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_PDSCH_ServingCellConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_PDSCH_ServingCellConfig_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetupRelease.h"

#endif	/* _PDSCH_ServingCellConfig_H_ */
#include <asn_internal.h>
