/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "./osc-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#include "PUSCH-ServingCellConfig.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_rateMatching_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_xOverhead_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_rateMatching_value2enum_3[] = {
	{ 0,	15,	"limitedBufferRM" }
};
static const unsigned int asn_MAP_rateMatching_enum2value_3[] = {
	0	/* limitedBufferRM(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_rateMatching_specs_3 = {
	asn_MAP_rateMatching_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_rateMatching_enum2value_3,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_rateMatching_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rateMatching_3 = {
	"rateMatching",
	"rateMatching",
	&asn_OP_NativeEnumerated,
	asn_DEF_rateMatching_tags_3,
	sizeof(asn_DEF_rateMatching_tags_3)
		/sizeof(asn_DEF_rateMatching_tags_3[0]) - 1, /* 1 */
	asn_DEF_rateMatching_tags_3,	/* Same as above */
	sizeof(asn_DEF_rateMatching_tags_3)
		/sizeof(asn_DEF_rateMatching_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_rateMatching_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rateMatching_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_xOverhead_value2enum_5[] = {
	{ 0,	4,	"xoh6" },
	{ 1,	5,	"xoh12" },
	{ 2,	5,	"xoh18" }
};
static const unsigned int asn_MAP_xOverhead_enum2value_5[] = {
	1,	/* xoh12(1) */
	2,	/* xoh18(2) */
	0	/* xoh6(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_xOverhead_specs_5 = {
	asn_MAP_xOverhead_value2enum_5,	/* "tag" => N; sorted by tag */
	asn_MAP_xOverhead_enum2value_5,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_xOverhead_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_xOverhead_5 = {
	"xOverhead",
	"xOverhead",
	&asn_OP_NativeEnumerated,
	asn_DEF_xOverhead_tags_5,
	sizeof(asn_DEF_xOverhead_tags_5)
		/sizeof(asn_DEF_xOverhead_tags_5[0]) - 1, /* 1 */
	asn_DEF_xOverhead_tags_5,	/* Same as above */
	sizeof(asn_DEF_xOverhead_tags_5)
		/sizeof(asn_DEF_xOverhead_tags_5[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_xOverhead_constr_5,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_xOverhead_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PUSCH_ServingCellConfig_1[] = {
	{ ATF_POINTER, 3, offsetof(struct PUSCH_ServingCellConfig, codeBlockGroupTransmission),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetupRelease_PUSCH_CodeBlockGroupTransmission,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"codeBlockGroupTransmission"
		},
	{ ATF_POINTER, 2, offsetof(struct PUSCH_ServingCellConfig, rateMatching),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_rateMatching_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"rateMatching"
		},
	{ ATF_POINTER, 1, offsetof(struct PUSCH_ServingCellConfig, xOverhead),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_xOverhead_5,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"xOverhead"
		},
};
static const int asn_MAP_PUSCH_ServingCellConfig_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_PUSCH_ServingCellConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PUSCH_ServingCellConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* codeBlockGroupTransmission */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rateMatching */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* xOverhead */
};
asn_SEQUENCE_specifics_t asn_SPC_PUSCH_ServingCellConfig_specs_1 = {
	sizeof(struct PUSCH_ServingCellConfig),
	offsetof(struct PUSCH_ServingCellConfig, _asn_ctx),
	asn_MAP_PUSCH_ServingCellConfig_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_PUSCH_ServingCellConfig_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PUSCH_ServingCellConfig = {
	"PUSCH-ServingCellConfig",
	"PUSCH-ServingCellConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_PUSCH_ServingCellConfig_tags_1,
	sizeof(asn_DEF_PUSCH_ServingCellConfig_tags_1)
		/sizeof(asn_DEF_PUSCH_ServingCellConfig_tags_1[0]), /* 1 */
	asn_DEF_PUSCH_ServingCellConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_PUSCH_ServingCellConfig_tags_1)
		/sizeof(asn_DEF_PUSCH_ServingCellConfig_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_PUSCH_ServingCellConfig_1,
	3,	/* Elements count */
	&asn_SPC_PUSCH_ServingCellConfig_specs_1	/* Additional specs */
};

