/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "./osc-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_RedirectedCarrierInfo_EUTRA_H_
#define	_RedirectedCarrierInfo_EUTRA_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-ValueEUTRA.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RedirectedCarrierInfo_EUTRA__cnType_r15 {
	RedirectedCarrierInfo_EUTRA__cnType_r15_epc	= 0,
	RedirectedCarrierInfo_EUTRA__cnType_r15_fiveGC	= 1
} e_RedirectedCarrierInfo_EUTRA__cnType_r15;

/* RedirectedCarrierInfo-EUTRA */
typedef struct RedirectedCarrierInfo_EUTRA {
	ARFCN_ValueEUTRA_t	 eutraFrequency;
	long	*cnType_r15;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RedirectedCarrierInfo_EUTRA_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cnType_r15_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RedirectedCarrierInfo_EUTRA;
extern asn_SEQUENCE_specifics_t asn_SPC_RedirectedCarrierInfo_EUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_RedirectedCarrierInfo_EUTRA_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RedirectedCarrierInfo_EUTRA_H_ */
#include <asn_internal.h>
