/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "./osc-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_UplinkConfig_H_
#define	_UplinkConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BWP-Id.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BWP_UplinkDedicated;
struct SetupRelease_PUSCH_ServingCellConfig;
struct SetupRelease_SRS_CarrierSwitching;
struct BWP_Uplink;

/* UplinkConfig */
typedef struct UplinkConfig {
	struct BWP_UplinkDedicated	*initialUplinkBWP;	/* OPTIONAL */
	struct UplinkConfig__uplinkBWP_ToReleaseList {
		A_SEQUENCE_OF(BWP_Id_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *uplinkBWP_ToReleaseList;
	struct UplinkConfig__uplinkBWP_ToAddModList {
		A_SEQUENCE_OF(struct BWP_Uplink) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *uplinkBWP_ToAddModList;
	BWP_Id_t	*firstActiveUplinkBWP_Id;	/* OPTIONAL */
	struct SetupRelease_PUSCH_ServingCellConfig	*pusch_ServingCellConfig;	/* OPTIONAL */
	struct SetupRelease_SRS_CarrierSwitching	*carrierSwitching;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UplinkConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UplinkConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_UplinkConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_UplinkConfig_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BWP-UplinkDedicated.h"
#include "SetupRelease.h"
#include "BWP-Uplink.h"

#endif	/* _UplinkConfig_H_ */
#include <asn_internal.h>
